### ISSUE TITLE
`/apply`: use modal instead of slash parameters

### ISSUE THREAD

**Issue by retronbv** [Chiroyce1/ModBot#3]
# Use a modal instead of slash parameters

[discordjs.guide example for modals](https://discordjs.guide/interactions/modals.html#building-and-responding-with-modals)

This could make better UX along with a native UI experience.

##### this was suggested in the chiroyce discord server

**Comment by Chiroyce1** [comment]
@Quantum-Codes want to try this if you want? I will help too :)

**Comment by Quantum-Codes** [comment]
Suree
